# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: æœµæœµå’Œé¹ä¸¾çš„å®¶
description: >- # this means to ignore newlines until "baseurl:"
  æˆ¿å±‹ä½¿ç”¨è¯´æ˜ä¹¦ã€‚
baseurl: "/bay" # the subpath of the site
url: "https://bigtoyscompany.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
#google_analytics: ""

header:
  pages:
    - name: å®¶ ğŸ 
      slug: /
    - name: ä¸»äºº ğŸ‘¸
      slug: /owner
    - name: æ‰‹å†Œ ğŸ“–
      slug: /manual

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: hi+duoduo@nai.ba
      link: mailto:hi+duoduo@nai.ba
    # - name: WeChat
    #   value: YourWeChatUsername
    #   link: "#"
  follow:
    # - name: Twitter
    #   link: http://twitter.com/YourTwitterUsername
    #   username: "@YourTwitterUsername"
    # - name: Facebook
    #   link: http://facebook.com/YourFacebookUsername
    # - name: LinkedIn
    #   link: http://linkedin.com/in/YourLinkedInUsername
    - name: GitHub
      link: http://github.com/naiba
    # - name: Dribbble
    #   link: https://dribbble.com/YourDribbbleUsername
    - name: RSS
      link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

future: true

# Used for defeating caching
version: 1
